auteur_index:
    path:     /
    defaults: { _controller: "KPLibBundle:Auteur:index" }
    methods:  GET

auteur_show:
    path:     /{id}/show
    defaults: { _controller: "KPLibBundle:Auteur:show" }
    methods:  GET

auteur_new:
    path:     /new
    defaults: { _controller: "KPLibBundle:Auteur:new" }
    methods:  [GET, POST]

auteur_edit:
    path:     /{id}/edit
    defaults: { _controller: "KPLibBundle:Auteur:edit" }
    methods:  [GET, POST]

auteur_delete:
    path:     /{id}/delete
    defaults: { _controller: "KPLibBundle:Auteur:delete" }
    methods:  DELETE
