KP\LibBundle\Entity\Auteur:
    type: entity
    table: null
    repositoryClass: KP\LibBundle\Repository\AuteurRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
        dateNaissance:
            type: date
            unique: true
            column: date_naissance
        idLivre:
            type: integer
            column: id_livre
    lifecycleCallbacks: {  }
